#!/usr/bin/env node
/**
 * Regenerates assets/generated/level-<id>.js from level-<id>.json.
 *
 * WHY THIS EXISTS. level-the-block.js opens with "AUTO-GENERATED by level build
 * step — do not edit by hand", and there was no level build step in the repo.
 * The .js and .json carried byte-identical payloads maintained by hand in two
 * places, with a header telling the next person not to touch either. This is
 * that missing step, following the same pattern as generate-cards.js and
 * generate-palette-json.js: the JSON is the source, the JS is a wrapper.
 *
 * Edit the JSON. Run this. Commit both.
 *
 * Usage: node scripts/generate-level.js            # all levels
 *        node scripts/generate-level.js the-block  # one level
 */
'use strict';

const fs = require('fs');
const path = require('path');

const GEN_DIR = path.join(__dirname, '..', 'assets', 'generated');

/**
 * Fields loadLevel() actually consumes, from level-loader.js. Anything in the
 * JSON outside this list is authoring metadata that never reaches the engine —
 * `title`, `tagline`, `design_pillar` and `experience` are documentation, and
 * `pois` / `consequence_matrix` are authored but not yet loaded (Sprint 2).
 * Listed here so the warning below can tell those two cases apart.
 */
const LOADED = new Set([
  'id', 'startLocationId', 'activeDistrictId', 'weather', 'timeOfDay',
  'districts', 'factions', 'locations', 'routes', 'characters',
  'scenarios', 'rumors', 'chains', 'threads', 'obligations',
  'events', 'vehicles', 'relationships'
]);
const KNOWN_UNLOADED = new Set([
  'title', 'tagline', 'design_pillar', 'experience',   // documentation
  'pois', 'consequence_matrix'                          // Sprint 2
]);

function generate(id) {
  const jsonPath = path.join(GEN_DIR, `level-${id}.json`);
  const jsPath = path.join(GEN_DIR, `level-${id}.js`);
  const raw = fs.readFileSync(jsonPath, 'utf8');

  let def;
  try {
    def = JSON.parse(raw);
  } catch (e) {
    throw new Error(`level-${id}.json is not valid JSON: ${e.message}`);
  }
  if (!def.id) throw new Error(`level-${id}.json has no .id`);

  const unexpected = Object.keys(def).filter(k => !LOADED.has(k) && !KNOWN_UNLOADED.has(k));
  if (unexpected.length) {
    console.warn(`  WARNING: ${unexpected.join(', ')} — not read by loadLevel() and not a known authoring field.`);
    console.warn('           Either wire it into level-loader.js or remove it; unread data drifts.');
  }

  const body = JSON.stringify(def, null, 2);
  const out = [
    '// AUTO-GENERATED by scripts/generate-level.js — do not edit by hand.',
    `// Source: assets/generated/level-${id}.json`,
    `// Concrete Kings — ${def.title || def.id} level definition (window.MAP_LEVEL).`,
    `window.MAP_LEVEL = ${body};`,
    ''
  ].join('\n');

  fs.writeFileSync(jsPath, out);
  return { jsPath, def };
}

const only = process.argv[2];
const ids = only
  ? [only]
  : fs.readdirSync(GEN_DIR)
      .filter(f => /^level-.+\.json$/.test(f))
      .map(f => f.replace(/^level-/, '').replace(/\.json$/, ''));

if (!ids.length) {
  console.error('No assets/generated/level-*.json found.');
  process.exit(1);
}

for (const id of ids) {
  const { jsPath, def } = generate(id);
  const counts = ['locations', 'routes', 'characters', 'scenarios', 'rumors', 'pois']
    .map(k => `${(def[k] || []).length} ${k}`)
    .join(' · ');
  console.log(`${path.basename(jsPath)}: ${counts}`);
}
