#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const DB_PATH = path.join(ROOT, 'CONCRETE-KINGS-CARD-DATABASE.md');
const INDEX_PATH = path.join(ROOT, 'index.html');
const OUT_PATH = path.join(ROOT, 'cards.js');

function readSection(text, startHeading, endHeading) {
  const start = text.indexOf(startHeading);
  if (start === -1) throw new Error(`Section not found: ${startHeading}`);
  const end = text.indexOf(endHeading, start + startHeading.length);
  if (end === -1) throw new Error(`End heading not found: ${endHeading}`);
  return text.slice(start, end);
}

function extractCardLines(section) {
  const lines = section.split('\n');
  const cards = [];
  for (const line of lines) {
    const m = line.match(/^\d+\.\s+(.+)$/);
    if (m) cards.push(m[1].trim());
  }
  return cards;
}

function stripEffectSuffix(text) {
  return text.replace(/\s+—\s+\*Effect:.*\*\s*$/, '').trim();
}

function ensureTrailingBlank(text) {
  return /____\s*$/.test(text) ? text : `${text} ____`;
}

function norm(s) {
  return s
    .trim()
    .toLowerCase()
    .replace(/\*\*/g, '')
    .replace(/[""]/g, '"')
    .replace(/['']/g, "'")
    .replace(/\s+/g, ' ')
    .replace(/[.?!]+$/g, '')
    .trim();
}

const STOPWORDS = new Set(['a', 'an', 'the', 'that', 'who', 'which', 'you', 'your', 'was', 'is', 'be', 'been', 'to', 'and', 'at']);

function wordSet(text) {
  return new Set(
    norm(text)
      .split(/[^a-z0-9]+/)
      .filter(w => w && !STOPWORDS.has(w))
  );
}

function jaccard(a, b) {
  const inter = [...a].filter(w => b.has(w)).length;
  const union = new Set([...a, ...b]).size;
  return union === 0 ? 0 : inter / union;
}

function dedupe(items) {
  const seen = new Set();
  const kept = [];
  for (const text of items) {
    const key = norm(text);
    if (!key || seen.has(key)) continue;
    seen.add(key);
    kept.push(text);
  }
  return kept;
}

function fuzzyDedupe(items, threshold = 0.72) {
  const kept = [];
  const keptWords = [];
  for (const text of items) {
    const ws = wordSet(text);
    let isDup = false;
    for (const kw of keptWords) {
      if (jaccard(ws, kw) >= threshold) {
        isDup = true;
        break;
      }
    }
    if (!isDup) {
      kept.push(text);
      keptWords.push(ws);
    }
  }
  return kept;
}

function extractExistingArray(indexHtmlSource, constName) {
  const re = new RegExp(`const ${constName} = \\[([\\s\\S]*?)\\n\\];`);
  const m = indexHtmlSource.match(re);
  if (!m) throw new Error(`Could not find ${constName} in index.html`);
  const body = m[1];
  const items = [];
  const itemRe = /"((?:[^"\\]|\\.)*)"/g;
  let im;
  while ((im = itemRe.exec(body))) {
    items.push(im[1].replace(/\\"/g, '"'));
  }
  return items;
}

function toJsArrayLiteral(items) {
  const lines = items.map(s => `  ${JSON.stringify(s)}`);
  return `[\n${lines.join(',\n')}\n]`;
}

function main() {
  const db = fs.readFileSync(DB_PATH, 'utf8');
  const indexHtml = fs.readFileSync(INDEX_PATH, 'utf8');

  const blackSection = readSection(db, '## Black Scenario Cards', '## White Response Cards');
  const whiteSection = readSection(db, '## White Response Cards', '## Receipt Chains');

  const blackFromDb = extractCardLines(blackSection).map(ensureTrailingBlank);
  const whiteFromDb = extractCardLines(whiteSection).map(stripEffectSuffix);

  const existingBlack = extractExistingArray(indexHtml, 'BLACK_CARDS');
  const existingWhite = extractExistingArray(indexHtml, 'WHITE_CARDS');

  const mergedBlack = fuzzyDedupe(dedupe([...existingBlack, ...blackFromDb]));
  const mergedWhite = fuzzyDedupe(dedupe([...existingWhite, ...whiteFromDb]));

  const output = `// Generated by scripts/generate-cards.js from CONCRETE-KINGS-CARD-DATABASE.md
// Do not hand-edit — re-run the generator instead:
//   node scripts/generate-cards.js
const BLACK_CARDS = ${toJsArrayLiteral(mergedBlack)};

const WHITE_CARDS = ${toJsArrayLiteral(mergedWhite)};
`;

  fs.writeFileSync(OUT_PATH, output);
  console.log(`Wrote ${OUT_PATH}`);
  console.log(`BLACK_CARDS: ${mergedBlack.length}`);
  console.log(`WHITE_CARDS: ${mergedWhite.length}`);
}

main();
